import type { RawPage } from './pages';

const QUALITY = [
  'Correct display on mobile, tablet and desktop',
  'Speed testing and optimization',
  'SEO fundamentals: titles, descriptions, structure, sitemap',
  'Security fundamentals and HTTPS',
  'Testing of forms, links and integrations',
  'Checks across different browsers',
];

export const PAGES_EN: RawPage[] = [
  {
    id: 'website',
    slug: 'website-development',
    kind: 'service',
    nav: 'Website development',
    title: 'Website Development in Georgia | Pricing, Timeline, Process | Webu',
    description: 'Website development from 480 GEL: landing pages and company websites built around your business goals. See what is included, how long it takes and how we work.',
    h1: 'Website development your business actually needs',
    answer: 'Webu builds landing pages and company websites for businesses in Georgia. A simple website starts from 480 GEL and a standard website from 1,200 GEL. A landing page takes about 2 weeks, a company website 4 to 6 weeks. Every site goes through a quality check before launch, and the domain, content and data belong to the client.',
    facts: [
      { k: 'Price', v: 'from 480 GEL · 40 GEL/month' },
      { k: 'Timeline', v: '2 to 6 weeks' },
      { k: 'Included', v: 'Design, development, SEO basics, testing' },
      { k: 'After launch', v: 'Webu Care support' },
    ],
    price: 'from 480 GEL',
    priceValue: 480,
    blocks: [
      {
        h2: 'Landing page or company website: which do you need?',
        p: ['It depends on what the site has to do. If you have one product or service and need to lead visitors to a single action, a landing page is enough. If your company has several services, directions or audiences, a company website is the better choice.'],
        table: {
          head: ['', 'Simple website (landing page)', 'Standard website (business site)'],
          rows: [
            ['Best for', 'One service, campaign or product', 'A company with several services'],
            ['Pages', 'One long page', 'Several pages and sections'],
            ['Timeline', 'About 2 weeks', '4 to 6 weeks'],
            ['Price', 'from 480 GEL', 'from 1,200 GEL'],
          ],
        },
      },
      {
        h2: 'What does website development at Webu include?',
        list: [
          'Getting to know your business and goals',
          'Site structure and content layout',
          'Custom design, not a ready-made template',
          'Development and a mobile version',
          'Contact forms and the integrations you need',
          'An admin panel if you want to manage content yourself',
          'SEO fundamentals and analytics setup where agreed',
          'Testing and launch',
        ],
      },
      {
        h2: 'How does the website development process work?',
        p: ['First we understand your business, then we build the right solution for it. No project starts without a clear scope: before we begin, we put in writing what is included, what is not, the timeline, the cost and the number of revisions.'],
        list: [
          'Discovery and scope: goals, features, proposal',
          'Design and UX: structure and a prototype you approve before any code is written',
          'Development and testing: you see working versions along the way',
          'Launch and support: we launch the site and stay with you',
        ],
      },
      {
        h2: 'How is website quality checked before launch?',
        p: ['Every website is tested before launch. We measure quality instead of just claiming it.'],
        list: QUALITY,
      },
      {
        h2: 'Who owns the website after it is built?',
        p: ['The domain, content and data are yours. Rights to the code and any third-party licenses are set out clearly in the contract. You have access to the relevant accounts, so you are never locked in to a single provider.'],
      },
    ],
    faqs: [
      { q: 'How much does a website cost?', a: 'A simple website (landing page) starts from 480 GEL and a standard website from 1,200 GEL. The final price depends on the number of pages, features, integrations and design complexity, and is set once the scope is agreed.' },
      { q: 'How long does it take to build a website?', a: 'A landing page takes about 2 weeks, a company website 4 to 6 weeks. You get an exact schedule after our first meeting.' },
      { q: 'Can I manage the website myself?', a: 'Yes. When needed, the site comes with an admin panel so you can update texts, photos and products yourself.' },
      { q: 'What happens after launch?', a: 'Launch is not the end of the relationship. Webu Care covers monitoring, backups, updates and bug fixes.' },
      { q: 'I already have a website. Can you improve it?', a: 'Yes. We start by assessing your current site, then decide together whether to update it or rebuild it. For a quick assessment you can use our free SEO audit.' },
    ],
    cta: 'Tell us about your website',
    related: ['store', 'seo', 'care', 'cost'],
  },
  {
    id: 'store',
    slug: 'online-store-development',
    kind: 'service',
    nav: 'Online store development',
    title: 'Online Store Development in Georgia | Payments, Inventory, Delivery | Webu',
    description: 'Online store development for businesses in Georgia: payments through Georgian banks, inventory and delivery management, and an admin panel. See what is included and how we work.',
    h1: 'Online store development that turns into manageable sales',
    answer: 'Webu builds online stores for businesses in Georgia, with payments through Georgian banks, inventory and delivery management, and an admin panel for managing products yourself. An online store usually takes 2 to 3 months, and the price depends on the number of products and the integrations you need.',
    facts: [
      { k: 'Timeline', v: '2 to 3 months' },
      { k: 'Payments', v: 'Through Georgian banks' },
      { k: 'Management', v: 'Admin panel' },
      { k: 'Price', v: 'from 1,920 GEL · 160 GEL/month' },
    ],
    price: 'from 1,920 GEL',
    priceValue: 1920,
    blocks: [
      {
        h2: 'What does building an online store include?',
        list: [
          'Product catalog with categories, filters and search',
          'Product pages with photos, descriptions and variants',
          'Cart and a simple checkout',
          'Online payments through Georgian banks',
          'Inventory and order management',
          'Delivery settings',
          'Admin panel for products, prices and orders',
          'SEO fundamentals for categories and products',
        ],
      },
      {
        h2: 'What is agreed before building an online store?',
        p: ['An online store involves many details, so before we begin we agree the scope together: the approximate number of products, payment methods, delivery rules, the integrations you need (for example accounting or warehouse systems) and who will add the products. You then get an exact proposal with price and timeline.'],
      },
      {
        h2: 'How is an online store tested before launch?',
        p: ['A bug in a store hits sales directly, so before launch we test the full order flow, including payment.'],
        list: [...QUALITY, 'An end-to-end test order and payment'],
      },
      {
        h2: 'What happens after an online store launches?',
        p: ['A store needs ongoing care: updates, backups and a fast response when something goes wrong. That is what Webu Care is for.'],
      },
    ],
    faqs: [
      { q: 'How long does it take to build an online store?', a: 'Usually 2 to 3 months. It depends on the number of products, integrations and design complexity. You get an exact schedule after our first meeting.' },
      { q: 'How much does an online store cost?', a: 'The price is set by the scope: how many products and categories, which payment and delivery methods you need and which systems the store must connect to. You get an exact proposal after our first meeting.' },
      { q: 'Can I add products myself?', a: 'Yes. The store comes with an admin panel for managing products, prices, inventory and orders yourself.' },
      { q: 'Which payment methods can be added?', a: 'Online payments through Georgian banks. We choose the specific methods based on your needs and your agreement with the bank.' },
    ],
    cta: 'Discuss your store with us',
    related: ['website', 'seo', 'care'],
  },
  {
    id: 'webapp',
    slug: 'web-app-development',
    kind: 'service',
    nav: 'Web app development',
    title: 'Web App Development | Booking Systems, Portals, Internal Tools | Webu',
    description: 'Web app development for your business process: online booking systems, client portals and internal tools. We understand the process first, then choose the technology.',
    h1: 'Web app development for your business process',
    answer: 'Webu builds web applications that simplify a specific business process: online booking systems, client portals and internal tools. First we understand what problem the app solves and what result you need, then we choose the technology. Price and timeline are set once the scope is agreed.',
    facts: [
      { k: 'Examples', v: 'Booking system, portal, internal tool' },
      { k: 'Approach', v: 'Business first, then technology' },
      { k: 'Price and timeline', v: 'from 3,000 GEL · 250 GEL/month' },
    ],
    price: 'from 3,000 GEL',
    priceValue: 3000,
    blocks: [
      {
        h2: 'When do you need a web app rather than a website?',
        p: ['A website informs and encourages visitors to get in touch. A web app does work: it takes bookings, calculates, stores data, tracks statuses and sends notifications automatically. If your team spends hours every day on manual work in spreadsheets and messengers, that is a sign you need a web app.'],
      },
      {
        h2: 'What kinds of web apps does Webu build?',
        list: [
          'Online booking systems: calendar, available slots, confirmations and reminders',
          'Client portals: for viewing orders, documents and statuses',
          'Internal tools: admin panels, reports and process automation',
          'Multi-step forms and application systems',
        ],
      },
      {
        h2: 'How does web app development work?',
        p: ['We do not sell technology to clients, we sell results. The logic is: business → problem → goal → solution → technology.'],
        list: [
          'Discovery: we study the current process and where time is lost',
          'Scope: we define features, user roles, integrations and what is not included',
          'Design and prototype: you approve the screens before any code is written',
          'Development and testing: you see working versions along the way',
          'Launch and Webu Care',
        ],
      },
      {
        h2: 'How is a web app kept secure?',
        p: ['Security is a baseline requirement, not a premium add-on. Depending on the product we use secure authentication, access roles, input validation, protected storage of secret keys and backups.'],
      },
    ],
    faqs: [
      { q: 'How much does a web app cost?', a: 'The price of a web app depends on its features, user roles, integrations and the amount of data. You get an exact price and timeline once the scope is agreed.' },
      { q: 'What is the difference between a website and a web app?', a: 'A website mainly provides information. A web app lets users get a specific job done: booking, managing orders, processing data. Often the two go together.' },
      { q: 'Who owns the app code and data?', a: 'The data is yours. Rights to the code and any third-party licenses are set out clearly in the contract, so you do not depend on a single provider.' },
    ],
    cta: 'Tell us about your process',
    related: ['mobile', 'website', 'care'],
  },
  {
    id: 'mobile',
    slug: 'mobile-app-development',
    kind: 'service',
    nav: 'Mobile app development',
    title: 'Mobile App Development for iOS and Android | Price, Timeline | Webu',
    description: 'Mobile app development for iOS and Android from 6,000 GEL: from design to release on the App Store and Google Play, with support after launch.',
    h1: 'Mobile app development for iOS and Android',
    answer: 'Webu builds mobile apps for iOS and Android, from design to release on the App Store and Google Play. Mobile app development starts from 6,000 GEL, usually takes 2 to 3 months, and after launch Webu Care keeps the app supported.',
    facts: [
      { k: 'Price', v: 'from 6,000 GEL · 500 GEL/month' },
      { k: 'Timeline', v: '2 to 3 months' },
      { k: 'Platforms', v: 'iOS and Android' },
      { k: 'Included', v: 'Release on the App Store and Google Play' },
    ],
    price: 'from 6,000 GEL',
    priceValue: 6000,
    blocks: [
      {
        h2: 'What does mobile app development include?',
        list: [
          'Understanding the idea and the business goal',
          'Scope: features, screens, user journey',
          'UI/UX design and an interactive prototype',
          'Development for iOS and Android',
          'Testing on real devices',
          'Release on the App Store and Google Play',
          'Support and updates after launch',
        ],
      },
      {
        h2: 'Do you actually need an app?',
        p: ['An app is worth it when customers use it often: for ordering, booking, a loyalty card or a personal account. If customers only visit you once, a good website or web app is often the better choice. We discuss this honestly at the first meeting.'],
      },
      {
        h2: 'How is a mobile app tested and released?',
        p: ['Before release we test the app on different screen sizes, on slow connections and in error situations. We take care of the App Store and Google Play review requirements.'],
      },
    ],
    faqs: [
      { q: 'How much does mobile app development cost?', a: 'Mobile app development starts from 6,000 GEL. The final price depends on the number of screens, features, integrations and design complexity.' },
      { q: 'How long does it take to build an app?', a: 'Usually 2 to 3 months. You get an exact schedule once the scope is agreed.' },
      { q: 'Do you publish the app on the App Store and Google Play?', a: 'Yes, release is part of the service. Developer accounts are opened in your name so the app remains your property.' },
      { q: 'What happens after launch?', a: 'Webu Care handles compatibility with new iOS and Android versions, updates and bug fixes.' },
    ],
    cta: 'Discuss your app idea with us',
    related: ['webapp', 'care', 'website'],
  },
  {
    id: 'design',
    slug: 'design-and-branding',
    kind: 'service',
    nav: 'Design and branding',
    title: 'UI/UX Design, Branding and Logo | Webu',
    description: 'UI/UX design, branding, logo and website redesign. An interactive prototype and design system before any code is written.',
    h1: 'Design and branding: UI/UX, logo and redesign',
    answer: 'Webu designs interfaces and brand visual language: UI/UX design, branding, logo and redesign of existing websites. You see every screen in an interactive prototype and approve it before any code is written. Pricing depends on the scope of the project.',
    facts: [
      { k: 'Covers', v: 'UI/UX, branding, logo, redesign' },
      { k: 'Result', v: 'Prototype and design system' },
      { k: 'Price', v: 'Logo 420 GEL (35/month), branding from 1,200 GEL (100/month)' },
    ],
    price: 'from 420 GEL',
    priceValue: 420,
    blocks: [
      {
        h2: 'What do design and branding at Webu include?',
        list: [
          'UI/UX: user journey, site structure and an interactive prototype',
          'Design system: colors, fonts and components that work the same on every page',
          'Branding: a visual language that sets you apart',
          'Logo and rules for using it',
          'Redesign: updating an existing site based on analysis',
        ],
      },
      {
        h2: 'Why does design come before code?',
        p: [
          'A change at the design stage is far cheaper and faster than after the code is written. So we build the structure and prototype first, you review every screen, and development starts only after your approval.',
        ],
      },
    ],
    faqs: [
      { q: 'Can I order design only?', a: 'Yes. You can order design separately and hand it to your own developer, or we can build it too.' },
      { q: 'What do I get at the end?', a: 'Design files, an interactive prototype and a design system. For branding, logo files and usage rules.' },
      { q: 'When is a redesign worth it?', a: 'When the site looks dated, is awkward on mobile or visitors cannot find what they need. We analyze it first and tell you whether a redesign is enough.' },
    ],
    cta: 'Discuss design with us',
    related: ['website', 'store', 'webapp'],
  },
  {
    id: 'seo',
    slug: 'seo-aeo-geo',
    kind: 'service',
    nav: 'SEO, AEO & GEO',
    title: 'SEO, AEO & GEO Optimization | Google and AI Search | Webu',
    description: 'SEO, AEO and GEO optimization: higher rankings on Google, direct answers in search and visibility in ChatGPT, Gemini and Perplexity. From 349 GEL/month, starting with a free audit.',
    h1: 'SEO, AEO & GEO: be found on Google and in AI search',
    answer: 'SEO improves your site’s rankings on Google. AEO (Answer Engine Optimization) prepares content so search engines and assistants show a direct answer from your site. GEO (Generative Engine Optimization) increases the chance that ChatGPT, Gemini, Perplexity and other AI assistants mention your business. Webu does all three together, starting from 349 GEL/month.',
    facts: [
      { k: 'Price', v: 'from 349 GEL/month' },
      { k: 'Covers', v: 'SEO, AEO and GEO' },
      { k: 'First step', v: 'Free audit' },
      { k: 'Available for', v: 'New and existing websites' },
    ],
    price: 'from 349 GEL/month',
    priceValue: 349,
    blocks: [
      {
        h2: 'What is the difference between SEO, AEO and GEO?',
        table: {
          head: ['', 'SEO', 'AEO', 'GEO'],
          rows: [
            ['Goal', 'High rankings in Google results', 'Direct answers in search and assistants', 'Mentions and citations in AI answers'],
            ['Where it shows', 'Google, Bing', 'Google answer boxes, voice assistants', 'ChatGPT, Gemini, Perplexity, Claude, Copilot'],
            ['Depends on', 'Technical health, content, links', 'Clear questions and answers, structure', 'Trustworthy, factual, easily quotable content'],
          ],
        },
      },
      {
        h2: 'What does Webu do for SEO, AEO and GEO?',
        list: [
          'Technical audit: speed, indexing, mobile version, errors',
          'Site structure and pages for the questions your customers search for',
          'Titles, descriptions and internal links',
          'Structured data (Schema.org) so Google and AI understand exactly who you are',
          'Question-and-answer content that search can show directly',
          'Access for AI search crawlers and an llms.txt file',
          'Google Search Console and Bing Webmaster Tools setup',
          'Measuring results and reporting',
        ],
      },
      {
        h2: 'Why does GEO matter now?',
        p: ['More and more people ask AI assistants directly, for example: “Who builds websites in Tbilisi?” The assistant answers using sources that clearly explain who you are, what you do and why you can be trusted. If your site does not present this clearly, the assistant mentions a competitor instead.'],
      },
      {
        h2: 'What can no one promise you in SEO?',
        p: ['No one can honestly promise you first place on Google or a mention in ChatGPT. We improve everything that influences it and measure the results. You will usually notice the first changes within 4 to 8 weeks, and steady growth builds over 3 to 6 months.'],
      },
    ],
    faqs: [
      { q: 'What is AEO?', a: 'AEO (Answer Engine Optimization) means preparing content so Google and assistants show a direct answer to a user’s question from your site.' },
      { q: 'What is GEO?', a: 'GEO (Generative Engine Optimization) means optimizing your site and brand so ChatGPT, Gemini, Perplexity and other AI assistants mention your business in their answers and use your site as a source.' },
      { q: 'How much do SEO, AEO and GEO cost?', a: 'Pricing starts from 349 GEL/month. The final price depends on the size of the site, its current state and the competition in your field. You can take a free audit before you start.' },
      { q: 'When will results show?', a: 'You will usually notice the first changes within 4 to 8 weeks, and steady growth builds over 3 to 6 months.' },
      { q: 'Can you do SEO for a website someone else built?', a: 'Yes. SEO, AEO and GEO are available as a standalone service for existing websites. We start with an audit to find what needs fixing.' },
    ],
    cta: 'Take the free audit',
    related: ['website', 'care', 'cost'],
  },
  {
    id: 'growth',
    slug: 'ads-and-analytics',
    kind: 'service',
    nav: 'Google Ads, Meta Ads and analytics',
    title: 'Google Ads, Meta Ads, Analytics and CRO | Webu',
    description: 'Growth and marketing: SEO, Google Ads and Meta Ads, analytics setup and CRO (conversion rate optimization).',
    h1: 'Growth: ads, analytics and conversion',
    answer: 'Webu’s growth services cover SEO, Google Ads and Meta Ads, analytics setup and CRO (conversion rate optimization). The goal is to bring more of the right visitors to your site and turn more of them into orders or requests. Fees and ad budgets are set individually.',
    facts: [
      { k: 'Covers', v: 'SEO, Google Ads, Meta Ads, analytics, CRO' },
      { k: 'Ad budget', v: 'Set by you' },
      { k: 'Price', v: 'SEO 349 GEL/month, ads from 249 GEL/month' },
    ],
    blocks: [
      {
        h2: 'What do ads, analytics and CRO at Webu include?',
        list: [
          'SEO, AEO and GEO: visibility in Google and AI search',
          'Google Ads: campaigns for people already searching for your service',
          'Meta Ads: advertising on Facebook and Instagram',
          'Analytics: GA4, conversion and goal setup',
          'CRO: improving pages and forms so more visitors get in touch',
        ],
      },
      {
        h2: 'Why should ads, SEO and analytics work together?',
        p: [
          'Ads, SEO and the site itself depend on each other. A good ad on a weak page wastes money, and without analytics you cannot tell which channel works. So we look at all three as one picture.',
        ],
      },
    ],
    faqs: [
      { q: 'Is the ad budget included in the price?', a: 'No. The ad budget is paid directly to Google and Meta and you decide it. Our fee covers managing the campaigns.' },
      { q: 'Do you guarantee results?', a: 'Nobody can honestly promise a specific ranking or number of sales. We promise transparent reports: what was spent, what came in and what we change next.' },
      { q: 'What is CRO?', a: 'Conversion rate optimization: turning a larger share of visitors into customers. We find where people leave the site and improve those places.' },
    ],
    cta: 'Discuss growth with us',
    related: ['seo', 'website', 'store'],
  },
  {
    id: 'ai',
    slug: 'ai-and-automation',
    kind: 'service',
    nav: 'AI and automation',
    title: 'AI Chatbots and Business Automation | Webu',
    description: 'AI chatbots, assistants, document and image recognition, automation and API integrations for business.',
    h1: 'AI and automation for business',
    answer: 'Webu builds AI chatbots, assistants and automations: a chatbot on your site or in messengers, document and image recognition, connecting systems through APIs and automating repetitive work. Pricing depends on the task.',
    facts: [
      { k: 'Covers', v: 'Chatbots, assistants, recognition, automation, API' },
      { k: 'Where it runs', v: 'Website, messengers, internal systems' },
      { k: 'Price', v: 'Chatbot 720 GEL (60/month), automation from 360 GEL (30/month)' },
    ],
    price: 'from 360 GEL',
    priceValue: 360,
    blocks: [
      {
        h2: 'What AI solutions does Webu build for businesses?',
        list: [
          'An AI chatbot on your site or in messengers that answers from your own information',
          'Assistants for your team: searching documents and drafting texts',
          'Recognition: extracting data from documents, receipts and images',
          'Automation: requests, notifications and reports without manual work',
          'API integrations: CRM, accounting, banks, Telegram and other systems',
        ],
      },
      {
        h2: 'Where does business automation start?',
        p: [
          'We first find one specific process that wastes the most time. We measure it, automate it and check the result. Then we expand where it really helps.',
        ],
      },
    ],
    faqs: [
      { q: 'Is my data safe?', a: 'We give access only to the data the task needs and tell you in advance which services receive any information.' },
      { q: 'Can the chatbot give a wrong answer?', a: 'AI can make mistakes, so we limit its topics, give it only verified information and have it hand the conversation to a person in difficult cases.' },
      { q: 'Will it connect to my existing system?', a: 'If the system has an API or a way to export data, usually yes. We check first and tell you what is possible.' },
    ],
    cta: 'Discuss an AI project with us',
    related: ['webapp', 'website', 'care'],
  },
  {
    id: 'hosting',
    slug: 'hosting-and-infrastructure',
    kind: 'service',
    nav: 'Hosting and infrastructure',
    title: 'Hosting, Domain, SSL and Email | Webu',
    description: 'Hosting and infrastructure: domain, hosting, SSL, business email, cloud and backups. The first 3 months of hosting are free on every new project.',
    h1: 'Hosting and infrastructure',
    answer: 'Webu sets up and manages everything your site runs on: domain, hosting, SSL certificate, business email, cloud services and backups. On every new project the first 3 months of hosting are free. Day-to-day care is part of the Webu Care package.',
    facts: [
      { k: 'Covers', v: 'Domain, hosting, SSL, email, cloud, backup' },
      { k: 'Hosting', v: 'First 3 months free, then 19 GEL/month' },
      { k: 'Ownership', v: 'The domain and data are yours' },
    ],
    blocks: [
      {
        h2: 'What do hosting and infrastructure at Webu include?',
        list: [
          'Domain registration and DNS management',
          'Fast, reliable hosting',
          'An SSL certificate so the site opens over a secure connection',
          'Business email on your domain',
          'Cloud infrastructure for apps and databases',
          'Regular backups',
          'Moving an existing site from another host',
        ],
      },
      {
        h2: 'What is the difference between infrastructure and Webu Care?',
        p: [
          'Infrastructure is where your site runs. Webu Care is who looks after it every day: monitoring, updates and fixes. You can take both together.',
        ],
      },
    ],
    faqs: [
      { q: 'What happens after the 3 free months?', a: 'Hosting continues within the Webu Care package or separately on agreed terms. We tell you the cost in advance.' },
      { q: 'Whose name is the domain in?', a: 'The domain, content and data are yours.' },
      { q: 'Can you move my existing site?', a: 'Yes. We check the site first and plan the move so that site and email downtime is kept to a minimum.' },
    ],
    cta: 'Discuss hosting with us',
    related: ['care', 'website', 'store'],
  },
  {
    id: 'care',
    slug: 'webu-care',
    kind: 'service',
    nav: 'Webu Care',
    title: 'Webu Care | Website Support and Maintenance After Launch',
    description: 'Webu Care: website and app support after launch. Monitoring, backups, updates, bug fixes, content changes and priority support.',
    h1: 'Webu Care: support after launch',
    answer: 'Webu Care is Webu’s package for websites and apps after launch. It covers hosting, monitoring, backups, updates, bug fixes, content changes and priority support. On every new project the first 3 months of hosting are free. Other terms are defined individually for each project.',
    facts: [
      { k: 'For', v: 'Websites, stores and apps' },
      { k: 'Covers', v: 'Hosting, monitoring, backups, updates, fixes' },
      { k: 'Hosting', v: 'First 3 months free' },
      { k: 'Price', v: '49, 129 or 279 GEL/month' },
    ],
    blocks: [
      {
        h2: 'How much do Webu Care packages cost?',
        table: {
          head: ['Package', 'What it includes', 'Price'],
          rows: [
            ['Start', 'Hosting, SSL, backups, monitoring, updates', '49 GEL/month'],
            ['Business', 'Start + 3 hours of changes a month, priority support', '129 GEL/month'],
            ['Pro', 'Business + 8 hours of development a month, fast response', '279 GEL/month'],
          ],
        },
      },
      {
        h2: 'What does Webu Care include?',
        list: [
          'Hosting and SSL certificate (first 3 months free)',
          'Monitoring: we know when the site goes down or slows down',
          'Regular backups',
          'System and component updates',
          'Bug fixes',
          'Content changes',
          'Priority support',
          'Development hours for new features',
          'Analytics and continuous improvements',
        ],
      },
      {
        h2: 'Why does a website need support after launch?',
        p: ['A website or app is a living product. Browsers, phones and online services change constantly and new security risks appear. A site left without support gradually slows down, becomes outdated and vulnerable.'],
      },
      {
        h2: 'How do you know what is happening with your project?',
        p: ['A client should never have to ask, “Where is my project at?” With Webu Care you always know what was done, what is in progress, what we need from you and what comes next.'],
      },
    ],
    faqs: [
      { q: 'Is hosting included in Webu Care?', a: 'Yes. Webu Care includes hosting and an SSL certificate, and on every new project the first 3 months of hosting after launch are free.' },
      { q: 'How much does Webu Care cost?', a: 'Webu Care has three packages: Start at 49 GEL/month, Business at 129 GEL/month and Pro at 279 GEL/month. On new projects the first 3 months of hosting are free.' },
      { q: 'Can you support a website someone else built?', a: 'Yes, after assessing the existing site. We first check its technical condition so we know what we are taking responsibility for.' },
      { q: 'When do you need Webu Care?', a: 'If your website or app matters to your business, takes orders or is used by customers regularly, support is essential to keep it fast, secure and working.' },
    ],
    cta: 'Discuss support with us',
    related: ['website', 'store', 'seo'],
  },
  {
    id: 'cost',
    slug: 'website-cost',
    kind: 'guide',
    nav: 'How much does a website cost',
    title: 'How Much Does a Website Cost in 2026? A Complete Pricing Guide | Webu',
    description: 'How much a website costs in Georgia in 2026: what drives the price, the extra costs of domain and hosting, and what a landing page, company website or app costs at Webu.',
    h1: 'How much does a website cost in 2026',
    answer: 'The cost of a website depends on its type, the number of pages and features, design complexity, integrations and support. At Webu a simple website (landing page) starts from 480 GEL, a standard website from 1,200 GEL, a mobile app from 6,000 GEL, and SEO, AEO and GEO from 349 GEL/month. On top of that, plan for a domain, hosting and support after launch.',
    facts: [
      { k: 'Simple website', v: 'from 480 GEL' },
      { k: 'Standard website', v: 'from 1,200 GEL' },
      { k: 'Mobile app', v: 'from 6,000 GEL' },
      { k: 'SEO, AEO & GEO', v: 'from 349 GEL/month' },
    ],
    blocks: [
      {
        h2: 'How much does a website cost at Webu by type?',
        table: {
          head: ['What you need', 'Price', 'Over 12 months', 'Approx. timeline'],
          rows: [
            ['Landing page', 'from 480 GEL', '40 GEL/month', '1 to 2 weeks'],
            ['Business website', 'from 1,200 GEL', '100 GEL/month', '3 to 4 weeks'],
            ['Corporate website', 'from 2,280 GEL', '190 GEL/month', '5 to 8 weeks'],
            ['Online store', 'from 1,920 GEL', '160 GEL/month', '5 to 7 weeks'],
            ['Web app / CRM', 'from 3,000 GEL', '250 GEL/month', '6 to 12 weeks'],
            ['Mobile app', 'from 6,000 GEL', '500 GEL/month', '3 to 4 months'],
            ['SEO, AEO and GEO', 'from 349 GEL/month', 'Monthly', 'Results in 4 to 8 weeks'],
            ['Webu Care', 'from 49 GEL/month', 'Monthly', 'After launch'],
          ],
        },
        p: ['“From” means the starting price. The final cost is set once the scope is agreed and is fixed in writing before the project begins.', 'Paying in full takes 10% off the price, and a returning client’s second project is 20% off. You can also split the price over 12 months.'],
      },
      {
        h2: 'What does the cost of a website depend on?',
        list: [
          'Scope: how many pages and which features you need',
          'Design complexity: a standard structure or a fully custom design',
          'Development: forms, calculators, personal accounts, booking',
          'Integrations: payments, bank, CRM, warehouse, analytics',
          'Content: whether texts and photos are ready or need to be created',
          'Number of languages',
          'Testing and quality control',
          'Project management and support after launch',
        ],
      },
      {
        h2: 'What costs come on top of building a website?',
        p: ['Besides the development price, plan for the costs a website needs to run:'],
        list: [
          'Domain, for example .ge: an annual fee to the registrar',
          'Hosting: the server where the site runs',
          'Business email, if you need it',
          'Paid services, such as payment processing fees',
          'Support: updates, backups and fixes (Webu Care)',
        ],
      },
      {
        h2: 'Which is better: a cheap website or the right website?',
        p: ['The cheapest website often ends up the most expensive: it loads slowly, looks bad on mobile, cannot be found on Google or needs rebuilding within months. When comparing offers, ask besides the price: what is included, who owns the site and domain, what happens after launch and how quality is checked.'],
      },
      {
        h2: 'How do you plan a website budget?',
        list: [
          'Write down what the site must do: calls, orders, bookings or information',
          'Decide what is essential now and what can be added later',
          'Gather existing materials: logo, texts, photos',
          'Include the domain, hosting and support',
          'Estimate your budget with our calculator and ask for an exact proposal at a consultation',
        ],
      },
    ],
    faqs: [
      { q: 'How much does a landing page cost?', a: 'At Webu a simple website (landing page) starts from 480 GEL and takes about 2 weeks.' },
      { q: 'How much does a company website cost?', a: 'At Webu a standard (business) website starts from 1,200 GEL and takes 4 to 6 weeks.' },
      { q: 'Are the domain and hosting included in the price?', a: 'The domain and hosting are separate costs because they should be registered in your name. We help with setup and configuration.' },
      { q: 'How does payment work?', a: 'In stages: 40 percent at the start, 30 percent when the design is approved and the rest at launch. SEO and support are billed monthly.' },
    ],
    cta: 'Get an exact proposal',
    related: ['website', 'store', 'mobile', 'seo'],
  },
  {
    id: 'geo',
    slug: 'what-is-geo',
    kind: 'guide',
    nav: 'What is GEO',
    title: 'What Is GEO and How to Get Your Business Into ChatGPT and AI Search | Webu',
    description: 'GEO (Generative Engine Optimization) explained: how ChatGPT, Gemini and Perplexity choose sources, what Google says about AI Overviews, and practical steps to get AI to mention your business.',
    h1: 'What is GEO and how to get your business into AI search',
    answer: 'GEO (Generative Engine Optimization) means preparing your site and brand so ChatGPT, Gemini, Perplexity and Google’s AI Overviews mention your business and use your site as a source. According to Google’s official position, there are no special tricks for appearing in AI features: the page needs to be indexed, technically sound and full of helpful, trustworthy content. For ChatGPT search, OpenAI’s OAI-SearchBot must be able to access your site.',
    facts: [
      { k: 'GEO', v: 'Generative Engine Optimization' },
      { k: 'Where it applies', v: 'ChatGPT, Gemini, Perplexity, AI Overviews' },
      { k: 'Foundation', v: 'SEO + trustworthy, quotable content' },
    ],
    blocks: [
      {
        h2: 'How do SEO, AEO and GEO differ?',
        p: ['SEO is about classic search: ranking high in Google results. AEO (Answer Engine Optimization) is about direct answers: getting search or an assistant to answer a user’s question from your page. GEO is about generative assistants that write the answer themselves from several sources and often cite them.', 'All three rest on the same foundation: a technically sound website and content that genuinely helps people.'],
      },
      {
        h2: 'What does Google say about AI Overviews?',
        p: ['Google’s documentation states plainly that there are no additional requirements or special optimizations needed to appear in AI Overviews or AI Mode. The page must be indexed and eligible to be shown in Google Search with a snippet.', 'Google recommends the same fundamentals as regular SEO: people-first content, crawling allowed in robots.txt, internal links, a good page experience, important content in text form, accurate structured data and Google Business Profile information.'],
      },
      {
        h2: 'How does a website get into ChatGPT search?',
        p: ['OpenAI runs several crawlers with different purposes. OAI-SearchBot processes sites for ChatGPT search, and according to OpenAI’s documentation, a site that blocks this bot will not appear in ChatGPT search answers. GPTBot collects data for model training, and ChatGPT-User acts when a user asks ChatGPT to open a specific page.', 'These settings are independent: you can allow OAI-SearchBot for search and block GPTBot for training. According to OpenAI, it takes about 24 hours for a robots.txt change to take effect.'],
        table: {
          head: ['Crawler', 'Company', 'Purpose'],
          rows: [
            ['OAI-SearchBot', 'OpenAI', 'ChatGPT search results'],
            ['GPTBot', 'OpenAI', 'Model training'],
            ['ChatGPT-User', 'OpenAI', 'Opening a page at a user’s request'],
            ['Googlebot', 'Google', 'Google Search, including AI Overviews'],
            ['Google-Extended', 'Google', 'Gemini training and grounding'],
            ['PerplexityBot', 'Perplexity', 'Perplexity search'],
            ['ClaudeBot', 'Anthropic', 'Data for Claude'],
          ],
        },
      },
      {
        h2: 'Which 8 practical steps improve GEO?',
        list: [
          'Check robots.txt: AI search crawlers (OAI-SearchBot, PerplexityBot, Googlebot) must not be blocked',
          'Open every important page with a short, direct answer: who you are, what you do, what it costs and how long it takes',
          'Phrase headings as the questions people actually search: “How much does…”, “What is the difference…”',
          'State specific, verifiable facts: prices, timelines, process. Generic phrases are not quotable for AI',
          'Add structured data (Schema.org): Organization, Service, FAQPage, Article',
          'Create an llms.txt file: a short Markdown summary at the site root that gives AI the key information fast',
          'Keep brand information identical everywhere: website, Google Business Profile, social media, directories',
          'Measure results: check analytics for visitors from chatgpt.com, perplexity.ai and other AI sources',
        ],
      },
      {
        h2: 'What is llms.txt?',
        p: ['llms.txt is a standard proposed by Jeremy Howard in 2024: a Markdown file at the site root (/llms.txt) that gives large language models short, structured information about the site. The only required part is an H1 heading with the site name, optionally followed by a short summary and lists of links to key pages.', 'llms.txt does not replace SEO. It is an extra channel that helps AI agents understand a site quickly and accurately.'],
      },
      {
        h2: 'What can no one promise you about GEO?',
        p: ['No one can honestly promise that ChatGPT or Gemini will definitely mention your business: it depends on the question, the competition and how trustworthy the system considers your site. You can increase the chance and measure the result, exactly as with regular SEO.'],
      },
    ],
    faqs: [
      { q: 'What is GEO?', a: 'GEO (Generative Engine Optimization) means optimizing your site and brand so AI assistants such as ChatGPT, Gemini and Perplexity mention your business in their answers and use your site as a source.' },
      { q: 'Do AI Overviews need special optimization?', a: 'According to Google’s official documentation, no. The page must be indexed and eligible for a snippet; the rest is regular SEO: helpful content, technical soundness and structured data.' },
      { q: 'How do I get my site into ChatGPT search?', a: 'OAI-SearchBot must be allowed in robots.txt. According to OpenAI, sites that block this bot will not appear in ChatGPT search answers. After that, clear, factual and quotable content matters most.' },
      { q: 'If I block GPTBot, will I disappear from ChatGPT?', a: 'Not necessarily. GPTBot is for model training, while ChatGPT search uses OAI-SearchBot. According to OpenAI, these settings are independent.' },
      { q: 'How do I measure visitors coming from AI?', a: 'Check your analytics traffic sources: chatgpt.com, perplexity.ai, gemini.google.com, copilot.microsoft.com and others. Webu’s analytics shows these sources separately.' },
    ],
    cta: 'Check your website for free',
    related: ['seo', 'cwv', 'website'],
    sources: [
      { title: 'Google Search Central: AI features and your website', url: 'https://developers.google.com/search/docs/appearance/ai-features' },
      { title: 'Google Search Central: Creating helpful, reliable, people-first content', url: 'https://developers.google.com/search/docs/fundamentals/creating-helpful-content' },
      { title: 'OpenAI: Overview of OpenAI Crawlers', url: 'https://developers.openai.com/api/docs/bots' },
      { title: 'llms.txt: The /llms.txt file (Jeremy Howard)', url: 'https://llmstxt.org/' },
    ],
  },
  {
    id: 'cwv',
    slug: 'core-web-vitals',
    kind: 'guide',
    nav: 'Website speed and Core Web Vitals',
    title: 'Core Web Vitals Explained: Why a Slow Website Loses Customers | Webu',
    description: 'Core Web Vitals explained: LCP, INP and CLS, Google’s “good” thresholds, how to measure your website speed and the steps that improve it.',
    h1: 'Website speed and Core Web Vitals: a complete guide',
    answer: 'Core Web Vitals are Google’s three metrics for measuring real user experience: LCP (loading of the main content, good under 2.5 seconds), INP (response to user interaction, good under 200 milliseconds) and CLS (visual stability, good under 0.1). Google recommends meeting these thresholds for 75% of visits, measured separately on mobile and desktop.',
    facts: [
      { k: 'LCP', v: '≤ 2.5 seconds' },
      { k: 'INP', v: '≤ 200 milliseconds' },
      { k: 'CLS', v: '≤ 0.1' },
      { k: 'Measured at', v: 'the 75th percentile of visits' },
    ],
    blocks: [
      {
        h2: 'What are the three Core Web Vitals metrics?',
        table: {
          head: ['Metric', 'What it measures', 'Good result'],
          rows: [
            ['LCP (Largest Contentful Paint)', 'How quickly the main element of the page appears', 'Under 2.5 seconds'],
            ['INP (Interaction to Next Paint)', 'How quickly the page responds to taps and typing', 'Under 200 milliseconds'],
            ['CLS (Cumulative Layout Shift)', 'How much the page “jumps” while loading', 'Under 0.1'],
          ],
        },
        p: ['The thresholds come from web.dev’s official recommendations. Google suggests assessing the 75th percentile of visits: a metric is “good” if at least 75% of visits meet the threshold.'],
      },
      {
        h2: 'Why is website speed a business issue?',
        p: ['On a slow website people wait, get frustrated and often simply go back to search and a competitor. Mobile matters most: many visitors open websites on their phones over mobile data. Google’s guidance names a good page experience as one of the foundations of success in search.'],
      },
      {
        h2: 'How do you measure website speed?',
        list: [
          'PageSpeed Insights (pagespeed.web.dev): free, shows both lab data and real-user data when the site has enough traffic',
          'Google Search Console: the Core Web Vitals report for the whole site',
          'Lighthouse in Chrome DevTools: detailed technical analysis for developers',
          'Webu’s free SEO audit: a quick assessment of speed, SEO and security',
        ],
      },
      {
        h2: 'Why is a website slow?',
        list: [
          'Unoptimized images and videos: files that are too large and old formats (JPG and PNG instead of WebP and AVIF)',
          'Heavy templates and too many plugins loading dozens of scripts on every page',
          'CSS and JavaScript that block the page from rendering',
          'Slow hosting on a server far away from users',
          'Fonts that hide text until they load',
          'Elements without set dimensions, which make the page jump while loading (CLS)',
        ],
      },
      {
        h2: 'How does Webu improve website speed?',
        p: ['Speed is part of the mandatory quality check on every Webu project. A practical example from our own website: we prepared separate, lighter homepage videos for mobile, converted images to WebP and gave the main element high loading priority. We measure quality instead of just claiming it.'],
        list: [
          'Compressed images in modern formats',
          'A separate, lighter video for mobile',
          'Preloading the main element (LCP)',
          'Fewer and deferred scripts',
          'Fast hosting and a CDN',
        ],
      },
    ],
    faqs: [
      { q: 'What are Core Web Vitals?', a: 'Core Web Vitals are Google’s three metrics for assessing real user experience: LCP (loading speed), INP (responsiveness) and CLS (visual stability).' },
      { q: 'What is a good LCP?', a: 'According to web.dev, LCP is good when the main element of the page appears within 2.5 seconds of the page starting to load.' },
      { q: 'What did INP replace?', a: 'In 2024 INP replaced FID (First Input Delay) and now measures how quickly a page responds to all user interactions during a visit.' },
      { q: 'How can I check my website speed for free?', a: 'Use PageSpeed Insights or Webu’s free SEO audit, which checks speed along with SEO and security.' },
    ],
    cta: 'Check your website speed for free',
    related: ['geo', 'seo', 'website'],
    sources: [
      { title: 'web.dev: Web Vitals', url: 'https://web.dev/articles/vitals' },
      { title: 'Google Search Central: AI features and your website', url: 'https://developers.google.com/search/docs/appearance/ai-features' },
      { title: 'PageSpeed Insights', url: 'https://pagespeed.web.dev/' },
    ],
  },
  {
    id: 'landing',
    slug: 'landing-page-vs-company-website',
    kind: 'guide',
    nav: 'Landing page or company website',
    title: 'Landing Page vs Company Website: Which Does Your Business Need? | Webu',
    description: 'Landing page vs company website: how they differ, when each one is the better choice, what they cost and how long they take. A simple test to help you decide.',
    h1: 'Landing page or company website: which does your business need',
    answer: 'A landing page is a one-page website built for a single goal, such as selling one service, running a campaign or taking event registrations. A company website has several pages and presents the whole business: services, work, team and contacts. At Webu a simple website (landing page) starts from 480 GEL and takes about 2 weeks; a standard (business) website starts from 1,200 GEL and takes 4 to 6 weeks.',
    facts: [
      { k: 'Landing page', v: 'from 480 GEL · ~2 weeks' },
      { k: 'Company website', v: 'from 1,200 GEL · 4–6 weeks' },
    ],
    blocks: [
      {
        h2: 'How does a landing page differ from a company website?',
        table: {
          head: ['', 'Landing page', 'Company website'],
          rows: [
            ['Goal', 'One specific action', 'Presenting the whole company'],
            ['Structure', 'One long page', 'Several pages and sections'],
            ['SEO', 'One or two search phrases', 'Many phrases, a page for each service'],
            ['For ads', 'Excellent', 'Good, if each campaign has its own page'],
            ['Timeline at Webu', 'About 2 weeks', '4 to 6 weeks'],
            ['Price at Webu', 'from 480 GEL', 'from 1,200 GEL'],
          ],
        },
      },
      {
        h2: 'When is a landing page the better choice?',
        list: [
          'You have one product or service',
          'You are running an ad campaign on Facebook, Instagram or Google',
          'You need registrations for an event, course or promotion',
          'The business is new and you want to test the idea quickly',
          'The budget is limited and you need the site fast',
        ],
      },
      {
        h2: 'When is a company website the better choice?',
        list: [
          'You have several services or directions',
          'You want to show up on Google for many different phrases',
          'Clients check a lot before deciding: your work, team, process',
          'You need a blog, news or several languages',
          'The website is the main source of trust for partners and investors',
        ],
      },
      {
        h2: 'How can 3 questions help you choose?',
        p: ['Answer three questions. If the answer to two or more is “yes”, you most likely need a company website. If not, start with a landing page.'],
        list: [
          'Do you offer more than one service or product?',
          'Do you want people to find you on Google for different questions?',
          'Do clients need a lot of information before they decide?',
        ],
      },
      {
        h2: 'Can you start with a landing page and expand later?',
        p: ['Yes, and it is often the smartest route. The key is to build the landing page from the start so that new pages can be added easily. That is why at Webu we define the scope before we begin: what you need now and what you may need in the future.'],
      },
    ],
    faqs: [
      { q: 'What is a landing page?', a: 'A landing page is a one-page website built for one specific goal, such as selling a service, running a campaign or taking registrations.' },
      { q: 'How much do a landing page and a company website cost?', a: 'At Webu a simple website (landing page) starts from 480 GEL and a standard (business) website from 1,200 GEL. The final price is set once the scope is agreed.' },
      { q: 'Which is better for SEO?', a: 'For ranking on many search phrases a company website is better, because each service can have its own optimized page. A landing page works for one or two main phrases.' },
      { q: 'Which is better for advertising?', a: 'For an ad campaign a landing page is often better, because it keeps visitors focused on one goal without distracting links.' },
    ],
    cta: 'Discuss your website with us',
    related: ['website', 'cost', 'studio'],
  },
  {
    id: 'studio',
    slug: 'how-to-choose-a-web-studio',
    kind: 'guide',
    nav: 'How to choose a web studio',
    title: 'How to Choose a Web Studio: 12 Questions to Ask Before You Sign | Webu',
    description: 'How to choose a web studio or developer for your website: 12 questions to ask before signing a contract, and the warning signs that point to trouble.',
    h1: 'How to choose a web studio: 12 questions to ask before you sign',
    answer: 'When choosing a web studio, five things matter more than price: real work, a clear scope (what is included and what is not), who owns the site, domain and code, how quality is checked, and what happens after launch. Below are 12 questions to ask before you sign a contract.',
    blocks: [
      {
        h2: 'Which 12 questions should you ask a web studio?',
        list: [
          'Can you show me real, live websites you have built?',
          'What is included in the price and what is not? Can you put it in writing?',
          'How many revisions are included in design and development?',
          'How is extra work priced if we need something during the project?',
          'In whose name will the domain and hosting be registered?',
          'Who owns the code and content once the project is finished?',
          'Will the design be custom or a ready-made template?',
          'Will I be able to change texts and photos myself?',
          'How do you check quality before launch: mobile, speed, forms, security?',
          'Are SEO fundamentals and analytics setup included?',
          'What happens after launch: who fixes bugs and what does support cost?',
          'How will I know what stage the project is at?',
        ],
      },
      {
        h2: 'What warning signs should you watch for?',
        list: [
          'A price is quoted before they understand your business and goals',
          'There is no written scope, everything is “agreed” verbally',
          'The domain or hosting is in the provider’s name and you have no access',
          'They guarantee first place on Google',
          'Instead of real work there are only generic images and unverifiable “100+ happy clients”',
          'Support after launch is never mentioned',
        ],
      },
      {
        h2: 'Why does the scope matter most?',
        p: ['Most project problems start with unclear requirements: the client expects one thing, the provider delivers another. A good scope defines in writing what is being built, what is not included, the key features, timeline, cost, number of revisions, how extra work is priced, the client’s responsibilities and the support terms.', 'At Webu no project starts without a clear scope. It is one of our core principles.'],
      },
      {
        h2: 'What matters more: price or value?',
        p: ['The cheapest offer often turns out expensive: a site that is slow, looks bad on mobile or needs rebuilding within months means paying twice. Compare not only the price but also what it includes, who owns the result and what happens after launch.'],
      },
    ],
    faqs: [
      { q: 'What should I check when choosing a web studio?', a: 'Real work, a written scope, ownership of the domain and code, the quality-check process and support terms after launch.' },
      { q: 'In whose name should the domain be registered?', a: 'The domain should be in your name as the client, and you should have access to manage it. That way you do not depend on the provider.' },
      { q: 'Can anyone guarantee first place on Google?', a: 'No. Rankings depend on competition, Google’s algorithms and many factors a provider cannot fully control. An honest provider improves everything that influences rankings and measures the result.' },
    ],
    cta: 'Ask us these 12 questions',
    related: ['cost', 'landing', 'website'],
  },
  {
    id: 'about',
    slug: 'about',
    kind: 'page',
    nav: 'About us',
    title: 'About Webu: a Digital Studio in Tbilisi, Georgia | Webu',
    description: 'Webu is a digital studio in Tbilisi, Georgia: we build websites, online stores, web apps and mobile apps. Meet our approach, principles and quality standard.',
    h1: 'Your idea. Our expertise.',
    answer: 'Webu is a digital studio in Georgia that builds websites, online stores, web apps and mobile apps. Clients commission a digital product from Webu, and Webu manages the process from idea to launch and beyond. We do not compete on the lowest price. We compete on quality, process, responsibility, communication, design, technical execution and ongoing support.',
    facts: [
      { k: 'Who we are', v: 'A digital studio in Georgia' },
      { k: 'Who we work with', v: 'Small, mid-sized and growing businesses' },
      { k: 'Core principle', v: 'Business first, then technology' },
    ],
    blocks: [
      {
        h2: 'Small-team attention, big-agency quality standards',
        p: ['We work with small and mid-sized businesses and growing companies that value quality, reliability, good design, solid technical execution, a clear process and responsible communication.', 'We talk to clients in the language of business, not technical jargon. Our logic is: business → problem → goal → solution → technology.'],
      },
      {
        h2: 'Our 10 principles',
        list: [
          'Understand first, then build',
          'We speak the language of business, not technical jargon',
          'We never start a project without a clear scope',
          'We never compromise on baseline quality and security',
          'Simplicity beats unnecessary complexity',
          'We do what we promise',
          'The client always knows what stage the project is at',
          'We measure quality instead of just claiming it',
          'Launch is not the end of the relationship',
          'Every project should strengthen Webu’s reputation',
        ],
      },
      {
        h2: 'Webu Quality Standard',
        p: ['Every project goes through a quality check before launch. We do not make unverifiable promises such as “100% security” or “#1 in Georgia”.'],
        list: [...QUALITY, 'Error and loading states', 'Backups where needed'],
      },
      {
        h2: 'Ownership and trust',
        p: ['The client’s domain and data belong to the client. Clients have access to the relevant accounts and assets, and rights to the code and third-party licenses are set out clearly in the contract. We never use vendor lock-in as a sales strategy.'],
      },
      {
        h2: 'How we use AI',
        p: ['We actively use AI in our internal work: research, ideation, coding and testing. But AI is a tool: Webu is responsible for the final result, and every project is checked by people.'],
      },
    ],
    faqs: [
      { q: 'What does Webu do?', a: 'Webu builds websites, online stores, web apps and mobile apps, and offers SEO, AEO and GEO optimization and support after launch (Webu Care).' },
      { q: 'Who does Webu work with?', a: 'Mainly small and mid-sized businesses and growing companies in Georgia that need a professional digital product.' },
      { q: 'How is Webu different from other studios?', a: 'We do not compete on the lowest price. We compete with a clear process, a written scope, quality checks, transparent communication, protecting the client’s ownership and support after launch.' },
    ],
    cta: 'Start a project',
    related: ['website', 'studio', 'care'],
  },
  {
    id: 'privacy',
    slug: 'privacy-policy',
    kind: 'page',
    nav: 'Privacy',
    title: 'Privacy Policy | Webu',
    description: 'What data the Webu website collects, why we use it, who receives it and what rights you have.',
    h1: 'Privacy policy',
    answer: 'This policy explains what data the Webu website collects, why we use it and how we protect it. The site uses no advertising cookies, and statistics are collected without cookies and without storing IP addresses.',
    facts: [
      { k: 'Cookies', v: 'No advertising cookies' },
      { k: 'Contact', v: 'hello@webu.ge' },
      { k: 'Updated', v: '1 October 2026' },
    ],
    blocks: [
      {
        h2: 'Who processes your data?',
        p: [
          'The data is processed by Webu (“we”). Contact: hello@webu.ge, +995 32 219 22 70, 40 Zhiuli Shartava St., Tbilisi.',
        ],
      },
      {
        h2: 'What data does Webu collect?',
        list: [
          'When you book a consultation: your name, phone or email, the chosen date and time, and the package picked in the price calculator, if any',
          'When you request an SEO audit report: the website address, your email and the audit results',
          'In the chat assistant: the questions you ask, without your name, IP address or session. If you leave a request: your name, phone or email, what you need and the last messages of the conversation',
          'Anonymous statistics: pages viewed, country and city, device and browser type, and where you came from. We do not store IP addresses: visitors are counted with an anonymous code that changes every day',
        ],
      },
      {
        h2: 'Why does Webu use the data?',
        list: [
          'To answer your request and arrange the consultation',
          'To prepare and send the audit report',
          'To improve the site based on anonymous statistics',
          'To improve the chat assistant’s answers',
        ],
        p: [
          'We do not sell data or share it with third parties for advertising.',
        ],
      },
      {
        h2: 'Who receives the data?',
        list: [
          'Webu’s own server: website hosting and storage of requests and anonymous statistics',
          'Telegram: a notification to our team about a new request, including from the chat assistant',
          'Google PageSpeed Insights: the website address you enter in the audit, for analysis',
        ],
        p: [
          'Telegram and Google may have servers outside Georgia. They receive data only for the purposes listed.',
        ],
      },
      {
        h2: 'Does the site use cookies?',
        p: [
          'The site uses no advertising or tracking cookies. Only technical data is kept in your browser: an anonymous session code that is deleted when you close the tab, the chat assistant conversation, also deleted when you close the tab, and settings the site’s features need.',
        ],
      },
      {
        h2: 'How long is the data kept?',
        p: [
          'We keep requests as long as needed to communicate and work with you, and no longer than 2 years after the last contact, unless the law requires otherwise.',
        ],
      },
      {
        h2: 'What are your rights?',
        list: [
          'Get information about the data we process about you and a copy of it',
          'Ask for the data to be corrected or deleted',
          'Withdraw consent or restrict processing',
          'Complain to the Personal Data Protection Service of Georgia',
        ],
        p: [
          'To send a request, email hello@webu.ge.',
        ],
      },
    ],
    faqs: [
      { q: 'Do I need to accept cookies?', a: 'No. The site uses no advertising or tracking cookies, so there is no consent banner.' },
      { q: 'How do I delete my data?', a: 'Email hello@webu.ge from the phone number or email you used in your request, and we will delete it.' },
    ],
    cta: 'Write to us with a question',
    related: ['about', 'website', 'care'],
  },
];
