import type { Dict } from './ka';

const en: Dict = {
  meta: {
    title: 'Webu | Website, Web App & Mobile App Development in Georgia',
    description: 'Webu is a digital studio in Tbilisi, Georgia. We design and build websites, online stores, web apps and mobile apps around your business goals, from idea to launch and beyond.',
  },
  nav: {
    items: [
      { id: 'services', label: 'Services' },
      { id: 'work', label: 'Work' },
      { id: 'process', label: 'How we work' },
      { id: 'audit', label: 'SEO audit' },
      { id: 'price', label: 'Pricing' },
      { id: 'faq', label: 'FAQ' },
    ],
    cta: 'Start a project',
    menu: 'Menu',
    close: 'Close',
    main: 'Main navigation',
    home: 'Webu, home',
    language: 'Language',
  },
  hero: {
    l1: 'Websites',
    l2: 'Apps',
    l3a: '&',
    l3b: 'SEO',
    sub: 'We design and build professional websites, web apps and digital products shaped around your business goals and needs.',
    cta: 'Start a project',
    cta2: 'See our work',
    offer: 'Websites from 40 GEL/month · 3 months of free hosting · 10% off when you pay in full',
  },
  services: {
    h2: 'Everything your business needs in the digital world',
    sub: 'Eight directions, one team and one point of responsibility. From websites and apps to ads, AI and care after launch.',
    more: 'Learn more',
    web: { cat: 'WEB DEVELOPMENT', title: 'Websites', text: 'Landing pages, business and corporate websites, and custom sites that present your business clearly and lead visitors to the next step.', chips: ['Landing', 'Business website', 'Corporate', 'Custom website'], btn: 'Start', badge: 'Checked' },
    ecom: { cat: 'E-COMMERCE', title: 'Online stores', text: 'A store that sells: catalog, payments with Georgian banks, delivery and integrations with your systems.', items: ['Online store', 'Payments', 'Delivery', 'Integrations'] },
    soft: { cat: 'SOFTWARE', mobile: 'Mobile apps', title: 'Apps and systems', text: 'Software your business runs on every day: web and mobile apps, CRM, booking systems, dashboards and APIs.', items: ['Web apps', 'Mobile apps', 'CRM', 'Booking', 'Dashboards', 'API'] },
    ui: { cat: 'DESIGN', title: 'Design and branding', text: 'UI/UX, branding, logo and redesign. Structure, prototype and visual language before any code is written.', chips: ['UI/UX', 'Branding', 'Logo', 'Redesign'], btn: 'Button', color: 'Color', swatches: ['Lime', 'Violet', 'Dark'] },
    seo: { cat: 'GROWTH', query: 'website development tbilisi', title: 'Growth and marketing', text: 'SEO, Google Ads and Meta Ads, analytics and CRO: more of the right visitors and more requests from your site.', chips: ['SEO', 'Google Ads', 'Meta Ads', 'Analytics', 'CRO'] },
    ai: { cat: 'AI & AUTOMATION', title: 'AI and automation', text: 'AI chatbots, assistants, document and image recognition, and automation through APIs.', chips: ['AI chatbots', 'Assistants', 'Recognition', 'Automation', 'API'], q: 'How long does delivery take?', a: 'In Tbilisi, 1 to 2 business days. Would you like to place an order?' },
    infra: { cat: 'INFRASTRUCTURE', title: 'Hosting and infrastructure', text: 'Domain, hosting, SSL, email, cloud and backups. Everything your site runs on.', chips: ['Domain', 'Hosting', 'SSL', 'Email', 'Cloud', 'Backup'], badge: '3 months of free hosting' },
    care: { cat: 'SUPPORT', title: 'Webu Care', text: 'Maintenance, security, updates, monitoring and development after launch.', chips: ['Maintenance', 'Security', 'Updates', 'Monitoring', 'Development'] },
  },
  serp: {
    label: 'Google search results',
    rival: 'Competitor',
    you: 'Your business',
    yourUrl: 'your-site.com',
  },
  work: {
    h2: 'Selected work',
    prev: 'Previous project',
    next: 'Next project',
    all: 'All projects',
    items: [
      { name: 'Textile Market', cat: 'Online store' },
      { name: 'Fabra Service', cat: 'Web app, CRM' },
      { name: 'Tevzao', cat: 'Platform, fishing map' },
      { name: 'gemo.menu', cat: 'SaaS, QR menu for restaurants' },
    ],
  },
  projects: {
    label: 'Work',
    h2: 'Projects that are live',
    lead: 'Real recordings from sites that are already running and serving customers.',
    meta: 'Real recording from the site',
    title: 'All projects | Webu',
    description: 'Webu portfolio: web apps, platforms, a QR menu and websites. Real recordings from live sites.',
  },
  process: {
    h2: 'From idea to launch',
    steps: [
      { n: '01', title: 'Discovery and scope', time: 'about 1 week', text: 'First we learn your business and goals. Together we define what is included, what is not, the timeline and the cost.', out: ['Goals', 'Scope', 'Proposal'] },
      { n: '02', title: 'Design and UX', time: 'about 2 weeks', text: 'We create the structure and an interactive prototype. You see and approve every screen before any code is written.', out: ['Structure', 'Prototype', 'Mobile version'] },
      { n: '03', title: 'Development and testing', time: '3 to 8 weeks', text: 'You see a working version every week. Before launch the site is tested for mobile, speed, forms, links and security.', out: ['Working builds', 'QA', 'Your approval'] },
      { n: '04', title: 'Launch and Webu Care', time: 'after launch', text: 'We launch, verify and stay with you. Support and improvements continue after launch.', out: ['Launch', 'Monitoring', 'Support'] },
    ],
  },
  audit: {
    h2: 'How well does Google see you?',
    text: 'Enter your website address and get a quick assessment. We will send the full report within 24 hours.',
    placeholder: 'yoursite.com',
    urlLabel: 'Website address',
    check: 'Check',
    scanning: 'Scanning...',
    metrics: ['Speed', 'Technical SEO', 'Security', 'Content'],
    notes: { total: 'Overall score', checking: 'Checking', failed: 'Check failed', good: 'Good result', ok: 'Room to improve', bad: 'Needs attention' },
    step: 'Checking {m}',
    found: '{n} issues found. ',
    offer: 'Get the full report with recommendations by email within 24 hours.',
    email: 'Your email',
    emailLabel: 'Email',
    request: 'Get the report',
    sending: 'Sending...',
    thanks: 'Thank you! We will send the full report within 24 hours.',
    failed: 'The check could not be completed',
    sendFailed: 'Could not send',
  },
  price: {
    h2: 'Estimate your budget',
    need: 'What do you need?',
    typeLabel: 'Project type',
    extra: 'Add-ons',
    budget: 'Estimated budget',
    weeks: 'Timeline: about {n} weeks',
    from: 'from {p}',
    orMonthly: 'or {m}/mo',
    full: 'Pay in full',
    split: 'Split over 12 months',
    weeksShort: '~{n} weeks',
    breakdown: 'Breakdown',
    note: 'The final cost is set once the scope is agreed.',
    cta: 'Discuss your project',
    perkHosting: '3 months of free hosting',
    off: '−10%',
    was: 'instead of {p}',
    perkFull: '10% off when you pay in full',
    perkSecond: '20% off your second project',
    perkInstall: 'Split into 12 monthly payments',
    types: { land: 'Landing page', biz: 'Business website', corp: 'Corporate website', shop: 'Online store', app: 'Web app / CRM', mobile: 'Mobile app' },
    addons: { seo: 'SEO setup', lang: 'Multilingual', admin: 'Admin panel', brand: 'Branding', ai: 'AI chatbot', analytics: 'Analytics (GA4)' },
    perMonth: '/ month',
  },
  care: {
    label: 'Webu Care',
    h2: 'Hosting and care in one package',
    lead: 'After launch we look after everything: hosting, security, updates and fixes. You run the business, we run the site.',
    badge: '3 months',
    badgeText: 'free hosting',
    badgeNote: 'On every new project, for the first 3 months after launch.',
    includesTitle: 'What the package includes',
    includes: [
      'Hosting and SSL certificate',
      'Monitoring: we know if the site goes down or slows down',
      'Regular backups',
      'System and security updates',
      'Bug fixes',
      'Content changes',
      'Priority support',
    ],
    installTitle: '12-month payment split',
    installText: 'The project cost is split into 12 equal monthly payments, with nothing extra on top.',
    more: 'About Webu Care',
    cta: 'Start a project',
    installBig: '12×',
    price: 'Webu Care: from 49 GEL/month',
  },
  faq: {
    h2: 'Frequently asked questions',
    noAnswer: 'Didn’t find your answer?',
    write: 'Write to us and we will get back to you soon.',
    items: [
      { q: 'How much does a website cost?', a: 'It depends on the scope: the number of pages, features, integrations and design complexity. You get an exact proposal after our first meeting.' },
      { q: 'How long does it take to build a website?', a: 'A landing page takes about 2 weeks, a company website 4 to 6 weeks, an online store or app 2 to 3 months. You get an exact schedule after our first meeting.' },
      { q: 'Can I manage the website myself?', a: 'Yes. When needed, the site comes with an admin panel so you can update texts, photos and products yourself.' },
      { q: 'Who owns the final product?', a: 'The domain, content and data are yours. Rights to the code and any licenses are set out clearly in the contract.' },
      { q: 'What happens after launch?', a: 'We stay with you after launch. Webu Care covers monitoring, backups, updates and bug fixes.' },
      { q: 'What are SEO, AEO and GEO?', a: 'SEO optimizes your site for Google search so you rank higher. AEO (Answer Engine Optimization) prepares content so Google and voice assistants show direct answers from your site. GEO (Generative Engine Optimization) increases the chance that ChatGPT, Gemini, Perplexity and other AI assistants mention and cite your business. We offer all three as part of a new website or as a standalone service for an existing one.' },
      { q: 'When will SEO results show?', a: 'You will usually notice the first changes within 4 to 8 weeks, and steady growth builds over 3 to 6 months. We send a monthly report.' },
      { q: 'How does payment work?', a: 'In stages: 40 percent at the start, 30 percent when the design is approved and the rest at launch. SEO and support are billed monthly. You can also split the cost into 12 monthly payments. Paying in full gives a 10% discount, and your second project is 20% off.' },
      { q: 'I already have a website. Can you improve it?', a: 'Of course. We start by assessing your current site, then decide together whether to update it or rebuild it.' },
    ],
  },
  contact: {
    h2: 'Book a free 30-minute consultation',
    prevMonth: 'Previous month',
    nextMonth: 'Next month',
    months: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
    monthsGen: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
    weekdays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
    dayFormat: '{m} {d}',
    free: 'Available times (Tbilisi time)',
    yours: 'Your meeting',
    booked: 'Booked! We will be in touch soon',
    pickTime: 'pick a time',
    pickBoth: 'Pick a day and time',
    needContact: 'Enter your name and phone or email',
    name: 'Name',
    contact: 'Phone or email',
    confirm: 'Confirm',
    thanks: 'Thank you',
    sending: 'Sending...',
    failed: 'Could not send',
    quoteLabel: 'Selected package',
  },
  footer: {
    nav: 'Footer navigation',
    address: 'Tbilisi, 40 Zhiuli Shartava St.',
    work: 'Work',
    process: 'How we work',
    audit: 'SEO audit',
    privacy: 'Privacy',
    blog: 'Blog',
  },
  content: {
    home: 'Home',
    services: 'Services',
    blog: 'Blog',
    breadcrumb: 'breadcrumb',
    budget: 'Estimate your budget',
    faq: 'Frequently asked questions',
    sources: 'Sources',
    finalText: 'First we understand your business, then we build the right solution for it. The first 30-minute consultation is free.',
    start: 'Start a project',
    freeAudit: 'Free SEO audit',
    related: 'Read next',
    guide: 'Guide',
    service: 'Service',
    updated: 'Updated:',
    blogTitle: 'Blog: Websites, Apps, SEO and AI Search | Webu',
    blogDescription: 'Webu guides on building websites, pricing, apps, SEO and AI search, written in plain business language.',
    blogLead: 'Guides on building websites, pricing, apps, SEO and AI search, written in plain business language.',
  },
  notFound: {
    title: 'Page not found | Webu',
    h1: 'Page not found',
    text: 'The link may have changed or the page was removed. Try one of the pages below.',
    home: 'Home page',
  },
};

export default en;
